repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.1
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        exclude: |
          (?x)^(
              acouchbase_analytics/tests/|
              couchbase_analytics/tests/|
              tests/|
              couchbase_analytics_version.py
          )
        args:
          [
              --quiet
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./run-mypy"
        language: python
        additional_dependencies:
          - mypy~=1.16.1
          - pytest~=8.3.5
          - httpx~=0.28.1
          - aiohttp~=3.11.10
        types:
          - python
        require_serial: true
        verbose: true
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.19
    hooks:
      # Compile requirements
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements.in, --python-version, '3.9', --universal, -o, requirements.txt]
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in, --python-version, '3.9', --universal, -o, requirements-dev.txt]
        files: ^requirements-dev\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements-sphinx.in
        args: [requirements-sphinx.in, --python-version, '3.9', --universal, -o, requirements-sphinx.txt]
        files: ^requirements-sphinx\.(in|txt)$
