# This file automatically generated by
#    /Users/jaredcasey/GIT/couchbase/clients/python/analytics-python-client/couchbase_analytics_version.py
# at
#    2025-07-24 17:08:38.315069
__version__ = '0.0.1'
