# This file automatically generated by
#    /Users/jaredcasey/GIT/couchbase/clients/python/analytics-python-client/couchbase_analytics_version.py
# at
#    2025-06-13 16:27:15.151489
__version__ = '0.0.1'
