# This file automatically generated by
#    /Users/jaredcasey/GIT/couchbase/clients/python/analytics-python-client/./couchbase_analytics_version.py
# at
#    2025-07-02 15:23:28.150595
__version__ = '0.0.1'
